business_terms = {
    'Corporation': [
        'company', 'incorporated', 'corporation', 'corp.', 'corp', 'inc',
        '& co.', '& co', 'inc.', 's.p.a.', 'n.v.', 'a.g.', 'ag', 'nuf', 's.a.',
        's.f.', 'oao', 'co.', 'co'
    ],
    'General Partnership': [
        'soc.col.', 'stg', 'd.n.o.', 'ltda.', 'v.o.s.', 'a spol.',
        u've\xc5\x99. obch. spol.', 'kgaa', 'o.e.', 's.f.', 's.n.c.',
        's.a.p.a.', 'j.t.d.', 'v.o.f.', 'sp.j.', 'og', 'sd', ' i/s', 'ay',
        'snc', 'oe', 'bt.', 's.s.', 'mb', 'ans', 'da', 'o.d.', 'hb', 'pt'
    ],
    'Joint Stock / Unlimited': [
        'unltd', 'ultd', 'sal', 'unlimited', 'saog', 'saoc', 'aj', 'yoaj',
        'oaj', 'akc. spol.', 'a.s.'
    ],
    'Joint Venture': ['esv', 'gie', 'kv.', 'qk'],
    'Limited': [
        'pty. ltd.', 'pty ltd', 'ltd', 'l.t.d.', 'bvba', 'd.o.o.', 'ltda',
        'gmbh', 'g.m.b.h', 'kft.', 'kht.', 'zrt.', 'ehf.', 's.a.r.l.',
        'd.o.o.e.l.', 's. de r.l.', 'b.v.', 'tapui', 'sp. z.o.o.', 's.r.l.',
        's.l.', 's.l.n.e.', 'ood', 'oy', 'rt.', 'teo', 'uab', 'scs', 'sprl',
        'limited', 'bhd.', 'sdn. bhd.', 'sdn bhd', 'as', 'lda.', 'tov', 'pp'
    ],
    'Limited Liability Company': [
        'pllc', 'p.l.l.c.', 'pl', 'p.l.', 'llc', 'l.l.c.', 'plc.', 'plc', 'hf.', 'oyj', 'a.e.', 'nyrt.',
        'p.l.c.', 'sh.a.', 's.a.', 's.r.l.', 'srl.', 'aat', '3at', 'd.d.',
        's.r.o.', 'spol. s r.o.', 's.m.b.a.', 'smba', 'sarl', 'nv', 'sa',
        'aps', 'a/s', 'p/s', 'sae', 'sasu', 'eurl', 'ae', 'cpt', 'as', 'ab',
        'asa', 'ooo', 'dat', 'vat', 'zat', 'mchj', 'a.d.'
    ],
    'Limited Liability Limited Partnership': ['lllp', 'l.l.l.p.'],
    'Limited Liability Partnership':
    ['llp', 'l.l.p.', 'sp.p.', 's.c.a.', 's.c.s.'],
    'Limited Partnership': [
        'gmbh & co. kg', 'gmbh & co. kg', 'lp', 'l.p.', 's.c.s.', 's.c.p.a',
        'comm.v', 'k.d.', 'k.d.a.', 's. en c.', 'e.e.', 's.a.s.', 's. en c.',
        'c.v.', 's.k.a.', 'sp.k.', 's.cra.', 'ky', 'scs', 'kg', 'kd', 'k/s',
        'ee', 'secs', 'kda', 'ks', 'kb', 'kt'
    ],
    'Mutual Fund': ['sicav'],
    'No Liability': ['nl'],
    'Non-Profit': ['vzw', 'ses.', 'gte.'],
    'Private Company': ['private', 'pte', 'xk'],
    'Professional Association': ['p.a.', 'pa'],
    'Professional Corporation': ['p.c.', 'vof', 'snc', 'pc'],
    'Sole Proprietorship': [
        'e.u.', 's.p.', 't:mi', 'tmi', 'e.v.', 'e.c.', 'et', 'obrt', 'fie',
        'ij', 'fop', 'xt'
    ],
}

medical_terms = {
    'Doctor of Dental Surgery': ['d.d.s.', 'd.d.o.', 'dds', 'ddo'],
    'General Denistry': ['general denistry', 'dntst'],
    'Doctor of Medical Dentistry': ['d.m.d.', 'dmd'],
    'Doctor of Osteopathy': ['d.o.', 'do'],
    'Doctor of Podiatric Medicine': ['d.p.m.', 'dpm'],
    'Doctor of Medicine': ['dr.', 'dr', 'doctor of medicine'],
    'Fellow of the American Academy of Dermatology': ['f.a.a.d.', 'faad'],
    'Fellow of the American Academy of Emergency Medicine':
    ['f.a.a.e.m.', 'faaaem'],
    'Fellow of the American Academy of Family Physicians':
    ['f.a.a.f.p.', 'faafp'],
    'Fellow of the American College of Cardiologists': ['f.a.c.c.', 'facc'],
    'Fellow of the American College of Endocrinology': ['f.a.c.e.'],
    'Fellow of the American College of Emergency Physicians':
    ['f.a.c.e.p.', 'facep'],
    'Fellow of the American College of Gastroenterology': ['f.a.c.g.', 'facg'],
    'Fellow of the American College of Foot and Ankle Surgeons': [
        'f.a.c.f.a.s.', 'facfas'
    ],
    'Fellow of the American College of Obstetrics and Gynecologists': [
        'f.a.c.o.g.', 'facog'
    ],
    'Fellow of the American College of Osteopathic Surgeons': [
        'f.a.c.o.s.', 'facos'
    ],
    'Fellow of the American College of Physicians': ['f.a.c.p.', 'facp'],
    'Fellow of the American College of Chest Physicians': [
        'f.a.c.c.p.', 'faccp'
    ],
    'Fellow of the American College of Surgeons': ['f.a.c.s.', 'facs'],
    'Fellow of the American Society of Podiatric Surgeons': [
        'f.a.s.p.s.', 'fasps'
    ],
    'Fellow in Hospital Medicine': ['f.h.m.', 'fhm'],
    'Fellow of the International College of Surgeons': ['f.i.c.s.', 'fics'],
    'Fellow of the Society for Cardiovascular Angiography and Interventions': [
        'f.s.c.a.i.', 'fscai'
    ],
    'Fellow of the Society of Thoracic Surgeons': ['f.s.t.s.', 'fsts'],
    'Medical Doctor': ['m.d.', 'md'],
    'Master of Public Health': ['m.p.h.'],
    'Nurse Practitioner': [
        'n.p.', 'np', 'a.r.n.p', 'arnp', 'a.c.n.p', 'acnp', 'a.g.n.p', 'agnp',
        'c.f.n.p', 'cfnp'
    ],
    'Doctor of Optometry': ['o.d.', 'od'],
    'Orthodontist': ['orthdont'],
    'Physician Assistant': ['p.a.'],
    'Doctor of Philosophy': ['dphil', 'ph.d.', 'phd', 'ph d'],
    'Registered Nurse': [
        'r.n.', 'rn', 'a.p.r.n.', 'aprn', 'rn cnp', 'rn, cnp', 'rncp'
    ],
    'Doctor of Psychology': ['psyd', 'psy.d', 'psych'],
    'Medical Student Life Advisory Committee': ['mslac', 'ms, lac'],
    'Women'
    's Health Care Nurse Practitioner': ['whcnp', 'whnp'],
    'Certified Nurse Midwife': ['c.n.m.', 'cnm'],
    'Doctor of Audiology': ['a.u.d.', 'aud'],
    'Doctor of Chiropractic': ['d.c.', 'dc'],
    'Doctor of Physical Therapy': ['d.p.t.', 'dpt'],
    'Doctor of Science in Physical Therapy': ['d.s.c.p.t.', 'dscpt'],
    'Doctor of Science in Nursing': ['d.s.n.', 'dsn'],
    'Doctor of Veterinary Medicine': ['d.v.m.', 'dvm'],
    'Ear, Nose and Throat Specialist': ['e.n.t.', 'ent'],
    'General Practitioner': ['g.p.', 'gp'],
    'Gynecologist': ['gyn'],
    'Master of Surgery': ['ms'],
    'Obstetrician and Gynecologist': ['ob/gyn', 'obgyn', 'ob gyn'],
    'Doctor of Pharmacy': ['pharmd', 'pharm.d'],
    'Fellow Faculty of Radiologists': ['ffr'],
    'Fellow of the Royal College of Physicians and Surgeons of Canada': [
        'frcpsc'
    ],
    'Member Royal College of Obstetricians and Gynecologists': ['mrcog'],
    'Member Royal College of Surgeons': ['mrcs'],
    'Doctor of Divinity': ['dd'],
    'Doctor of Education': ['ded', 'edd'],
    'Doctor of Public Administration': ['dpa'],
    'Doctor of Public Health': ['dph'],
    'Fellow Faculty of Public Health Medicine': ['ffphm'],
    'Doctor of Jurisprudence': ['jd'],
    'Doctor of Science': ['scd'],
    'Doctor of Social Science': ['sscd'],
    'Doctor of Theology': ['thd'],
    'Certificate of Clinical Competence': ['ccc'],
    'Fellow of the American College of Obstetricians and Gynecologists': [
        'facog'
    ],
    'Family Nurse Practitioner': ['fncp'],
    'Licensed Clinical Professional Counselor': ['lcpc', 'lpc'],
    'Licensed Marriage and Family Therapist': ['lmft'],
    'Marriage, Family and Child Counselor': ['mfcc'],
    'Marriage and Family Therapists': ['mft'],
    'Licensed Mental Health Counselor': ['lmhc', 'lcmhc', 'cmhc'],
    'Licensed Mental Health Professional': ['lmhp'],
    'Licensed Professional Clinical Counselor': ['lpcc'],
    'Bachelor of Medicine': [
        'mbbs', 'mbchb', 'mbbch', 'mb bchir', 'bm bch', 'bmbs'
    ],
    'Occupational Therapist': ['otr', 'otrl', 'otr/l', 'otr l'],
    'Psychiatric-Mental Health Nurse Practitioner': ['pmhnp'],
    'Pediatric Nurse Practitioner': ['pnp'],
}

lawyer_terms = {
    'Juris Doctor': ['j.d.', 'jd'],
    'Bachelor of Laws': ['ll.b', 'llb', 'l.l.b.'],
    'Master of Laws': ['ll.m', 'llm', 'l.l.m.'],
    'Doctor of Juridical Studies': ['jsd', 'j.s.d.', 'sjd', 's.j.d.'],
    'Esquire': ['esq', 'esq.'],
    'Attorney': ['atty', 'attorney', 'attorney at law'],
    'Lawyer': ['lwyr', 'lawyer'],
}

real_estate_terms = {
    'Accredited Buyer Representative': ['abr'],
    'Accredited Management Organization': ['amo'],
    'Certified Buyer Representative': ['cbr'],
    'Certified Home Marketing Specialist': ['chms'],
    'Certified Luxury Home Marketing Specialist': ['clhms'],
    'Certified Negotiation Specialist': ['cns'],
    'Certified Property Manager': ['cpm'],
    'Certified Real Estate Broker': ['crb'],
    'Certified Residential Specialist': ['crs'],
    'Graduate Realtor Institute': ['gri'],
    'Graduate Real Estate Society': ['gres'],
    'Graduate REALTOR® Institute': ['gri'],
    'National Association of Realtors': ['nar'],
    'Member of the National Association of Realtors': ['realtor'],
    'Real Estate Board of New York': ['rebny'],
    'Realtors Political Action Committee': ['rpac'],
    'Senior Real Estate Specialist': ['sres'],
}

insurance_terms = {
    'Certified Insurance Counselor': ['cic'],
    'Certified Risk Manager': ['crm'],
    'Associate in Risk Management': ['arm'],
    'Associate In General Insurance': ['ains'],
    'Accredited Advisor in Insurance': ['aai'],
    'Personal Lines Coverage Specialist': ['plcs'],
    'Certified Insurance Service Representative': ['cisr'],
    'Associate in Insurance Services': ['ais'],
    'Associate in Claims': ['aic'],
    'Chartered Life Underwriter': ['clu'],
    'Life Underwriter Training Council Fellow': ['lutcf'],
    'Financial Services Certified Professional': ['fscp'],
    'Certified Financial Planner': ['cfp'],
    'Registered Health Underwriter': ['rhu'],
    'Professional, Health Insurance Advanced Studies': ['fhias'],
    'Professional, Academy for Healthcare Management': ['pahm'],
    'Chartered Healthcare Consultant': ['chhc'],
    'Healthcare Customer Service Associate': ['hcsa'],
    'Health Insurance Associate': ['hia'],
    'Healthcare Compliance Professional': ['hcp'],
    'Fellow, Life and Health Claims': ['flhc'],
    'Group Benefits Associate': ['gba'],
    'Managed Healthcare Professional': ['mhp'],
    'Chartered Property Casualty Underwriter': ['cpcu'],
    'Commercial Lines Coverage Specialist': ['clcs']
}

finance_terms = {
    'Accredited Adviser in Insurance': ['aai'],
    'Associate of the Academy of Life Underwriting': ['aalu'],
    'Accredited Asset Management Specialist': ['aams'],
    'Accredited Domestic Partnership Advisor': ['adpa'],
    'Accredited Estate Planner': ['aep'],
    'Associate Financial Advisor': ['afa'],
    'Accredited Financial Counselor': ['afc'],
    'Associate, Financial Services Institute': ['afsi'],
    'Accredited Investment Fiduciary': ['aif'],
    'Accredited Investment Fiduciary Analyst': ['aifa'],
    'Associate in Insurance Services': ['ais'],
    'Associate, Life and Health Claims': ['alhc'],
    'Associate, Life Management Institute': ['almi'],
    'Associate in Personal Insurance': ['api'],
    'Accredited Portfolio Management Advisor': ['apma'],
    'Asset Protection Planner': ['app'],
    'Accredited Pension Representative': ['apr'],
    'Accredited Retirement Advisor': ['ara'],
    'Associate in Research and Planning': ['arp'],
    'Accredited Retirement Plan Consultant': ['arpc'],
    'Accredited Tax Advisor': ['ata'],
    'Accredited Tax Preparer': ['atp'],
    'Accredited Wealth Management Advisor': ['awma'],
    'Board Certified in Annuities': ['bca'],
    'Board Certified in Asset Allocation': ['bcaa'],
    'Board Certified in Estate Planning': ['bce', 'bcep'],
    'Board Certified in Insurance': ['bci'],
    'Board Certified in Mutual Funds': ['bcm', 'bcmf'],
    'Board Certified in Securities': ['bcs'],
    '3 Dimensional Wealth Practitioner': ['c3dwp'],
    'Certified Annuity Advisor': ['caa'],
    'Certified Annuity Consultant': ['cac'],
    'Chartered Alternative Investment Analyst': ['caia'],
    'Chartered Asset Manager': ['cam'],
    'Chartered Advisor in Philanthropy': ['cap'],
    'Certified Asset Protection Analyst': ['capa'],
    'Certified Asset Protection Planner': ['capp'],
    'Certified Annuity Specialist': ['cas'],
    'Chartered Advisor for Senior Living': ['casl'],
    'Chartered Benefit Consultant': ['cbc'],
    'Certified Credit Counselor': ['ccc'],
    'Certified Christian Insurance Advisor': ['ccia'],
    'Certified College Planning Specialist': ['ccps'],
    'Certified Care Resource Specialist': ['ccrs'],
    'Certified Customer Service Representative': ['ccsr'],
    'Certified Divorce Financial Analyst': ['cdfa'],
    'Certified Divorce Planner': ['cdp'],
    'Certified Divorce Specialist': ['cds'],
    'Certified Estate Advisor': ['cea'],
    'Certified Employee Benefit Specialist': ['cebs'],
    'Certified Equity Indexed Annuity Specialist': ['ceias'],
    'Certified Estate Planner': ['cep'],
    'Certified Equity Professional': ['cep'],
    'Certified Exit Planning Advisor': ['cepa'],
    'Certified Educator in Personal Finance': ['cepf'],
    'Chartered Estate Planning Practitioner': ['cepp'],
    'Certified Elder Planning Specialist': ['ceps'],
    'Chartered Financial Analyst': ['cfa'],
    'Certified Family Business Specialist': ['cfbs'],
    'Certified Financial Consultant': ['cfc'],
    'Christian Financial Consultant & Advisor': ['cfca'],
    'Certified Financial Divorce Practitioner': ['cfdp'],
    'Certified Financial Educator': ['cfe or cfed'],
    'Certified Financial Examiner': ['cfex'],
    'Certified Financial Gerontologist': ['cfg'],
    'Certified Financial Health Counselor': ['cfhc'],
    'Certified Financial Management Analyst': ['cfla'],
    'Certified Financial Manager': ['cfm'],
    'Certified in Financial Management': ['cfm'],
    'Chartered and Certified Financial Management Analyst': ['cfma'],
    'Certified Financial Marketing Professional': ['cfmp'],
    'Certified Financial Planner': ['cfp'],
    'Certificate in Estate Planning Management': ['cfpm'],
    'Christian Financial Professionals Network Certified Member': ['cfpn'],
    'Certified Fund Specialist': ['cfs'],
    'Chartered Economist': ['che'],
    'Chartered Financial Consultant': ['chfc'],
    'Chartered Financial Engineer': ['chfe'],
    'Chartered Federal Employee Benefits Consultant': ['chfebc'],
    'Certified Healthcare Financial Professional': ['chfp'],
    'Certified Insurance Counselor': ['cic'],
    'Chartered Investment Counselor': ['cic'],
    'Certified Investment Management Consultant': ['cimc'],
    'Chartered Insurance Professional': ['cip'],
    'Certified IRA Specialist': ['ciras'],
    'Certified Income Specialist': ['cis'],
    'Certified Investment Strategist': ['cis'],
    'Certified IRA Services Professional': ['cisp'],
    'Certified Insurance Service Representative': ['cisr'],
    'Chartered Leadership Fellow': ['clf'],
    'Certified in Long-Term Care': ['cltc'],
    'Chartered Life Underwriter': ['clu'],
    'Chartered Market Analyst': ['cma'],
    'Certified Mortgage Coach': ['cmc'],
    'Chartered Mutual Fund Counselor': ['cmfc'],
    'Certified Mortgage Planning Specialist': ['cmps'],
    'Chartered Market Technician': ['cmt'],
    'Certified Public Accountant': ['cpa'],
    'Certified Personal Banker': ['cpb'],
    'Certified Pension Consultant': ['cpc'],
    'Certified Professional Consultant': ['cpc'],
    'Chartered Property Casualty Underwriter': ['cpcu'],
    'Certified Personal Finance Counselor': ['cpfc'],
    'Certified Professional in Financial Services': ['cpfs'],
    'Certified Philanthropic Developer': ['cphd'],
    'Certified Professional Insurance Agent': ['cpia'],
    'Chartered Portfolio and Investment Management': ['cpim'],
    'Certified Professional Insurance Woman/Man': ['cpiw/m'],
    'Chartered Portfolio Manager': ['cpm'],
    'Certified Professional Service Representative': ['cpsr'],
    'Certified Practitioner of Taxation': ['cptx'],
    'Certified Private Wealth Advisor': ['cpwa'],
    'Chartered Private Wealth Advisor': ['cpwa'],
    'Certified Retirement Counselor': ['crc'],
    'Certified Retirement Financial Advisor': ['crfa'],
    'Certified Retirement Planner': ['crp'],
    'Chartered Retirement Planning Counselor': ['crpc'],
    'Chartered Retirement Plans Specialist': ['crps'],
    'Certified Retirement Specialist': ['crs'],
    'Certified Retirement Services Professional': ['crsp'],
    'Certified Senior Advisor': ['csa'],
    'Certified Senior Consultant': ['csc'],
    'Certified Specialist in Estate Planning': ['csep'],
    'Certified Senior Financial Planner': ['csfp'],
    'Chartered Senior Financial Planner': ['csfp'],
    'Certified Specialist in Retirement Planning': ['csrp'],
    'Certified Senior Specialist': ['css'],
    'Certified Specialist in Tax Sheltered Accounts': ['cstsa'],
    'Chartered Trust and Estate Planner': ['ctep'],
    'Certified Trust and Financial Advisor': ['ctfa'],
    'Certified Tax Specialist': ['cts'],
    'Certified Wealth Consultant': ['cwc'],
    'Chartered Wealth Manager': ['cwm'],
    'Certified Workplace Money Coach': ['cwmc'],
    'Certified Wealth Transfer Practitioner': ['cwp'],
    'Certified Private Wealth Advisor': ['cwpa'],
    'Certified Wealth Preservation Manager': ['cwpm'],
    'Certified Wealth Preservation Planner': ['cwpp'],
    'Certified Wealth Strategist': ['cws'],
    'Certified Wealth Smart Strategist': ['cwss'],
    'Diversified Advanced Education': ['dae'],
    'Disability Income Associate': ['dia'],
    'Enrolled Agent': ['ea'],
    'Employee Healthcare Benefits Associate': ['ehba'],
    'Dave Ramsey Certified Counselor': ['drcc'],
    'Estate Law Specialist': ['els'],
    'Estate Planning Law Specialist': ['epls'],
    'Financial Analyst Designate': ['fad'],
    'Fellow of the Academy of Life Underwriting': ['falu'],
    'Fellow Chartered Insurance Professional': ['fcip'],
    'Family Foundation Specialist': ['ffs'],
    'Fellow, Financial Services Institute': ['ffsi'],
    'Fraternal Insurance Counselor': ['fic'],
    'Fraternal Insurance Counselor Fellow': ['ficf'],
    'Fellow, Life and Health Claims': ['flhc'],
    'Fellow, Life Management Institute': ['flmi'],
    'Financial Services Specialist': ['fss'],
    'Graduate Estate Planning Consultant': ['gepc'],
    'Health Insurance Associate': ['hia'],
    'Investment Fiduciary Auditor': ['ifa'],
    'Certificate in General Insurance': ['ins'],
    'Program in General Insurance': ['ins'],
    'LIMRA Leadership Institute Fellow': ['llif'],
    'Long-Term Care Group Specialist': ['ltcgs'],
    'Long Term Care Professional': ['ltcp'],
    'Certified Long Term Care Resource Specialist': ['ltcrs'],
    'Life Underwriter Training Counselor Fellow': ['lutcf'],
    'Master Certified Estate Planner': ['mcep'],
    'Master Certified Retirement Specialist': ['mcrs'],
    'Master Financial Advisor': ['mfa'],
    'Master Financial Manager': ['mfm'],
    'Master Financial Professional': ['mfp'],
    'Medicare Supplement Accredited Advisor': ['msaa'],
    'Macro Strategic Planner': ['msp'],
    'Master of Science in Financial Management': ['msfm'],
    'Master of Science in Financial Services': ['msfs'],
    'Private Annuity Trusts Adviser': ['pata'],
    'Professional Financial Advisor': ['pfa'],
    'Personal Financial Specialist': ['pfs', 'cpa/pfs'],
    'Professional Plan Consultant': ['ppc'],
    'Accredited Adviser in Insurance': ['pro'],
    'PLANSPONSOR Retirement Professional': ['prp'],
    'Personal Retirement Planning Specialist': ['prps'],
    'Professional Workers'' Compensation Advisor': ['pwca'],
    'Qualified Financial Advisor': ['qfa'],
    'Qualified Financial Planner': ['qfp'],
    'Qualified Plan Financial Consultant': ['qpfc'],
    'Registered Clergy Advisor': ['rca'],
    'Registered Employee Benefits Consultant': ['rebc'],
    'Registered Education Planner': ['rep'],
    'Registered Financial Associate': ['rfa'],
    'Registered Financial Consultant': ['rfc'],
    'Registered Financial Gerontologist': ['rfg'],
    'Registered Financial Planner': ['rfp'],
    'Registered Financial Specialist': ['rfs'],
    'Registered Health Underwriter': ['rhu'],
    'Registered Investor Coach': ['ric'],
    'Retirement Income Specialist': ['ris'],
    'Registered Mortgage Advisor': ['rma'],
    'Retirement Management Analyst': ['rma'],
    'Registered Mortgage Underwriter': ['rmu'],
    'Registered Paraplanner': ['rp'],
    'Retirement Plans Associate': ['rpa'],
    'Registered Para Planner': ['rpp'],
    'Senior Registered Financial Planner': ['srfp'],
    'Wealth Management Specialist': ['wms'],
    'Certified Public Accountant': ['c.p.a', 'cpa', 'certified public accountant'],
    'Financial Advisor': ['financial advisor'],
}

other_terms = {
    'Academy of Certified Social Workers': ['a.c.s.w.', 'acsw'],
    'Licensed Clinical Social Worker':
    ['lcsw', 'lcsw-c', 'lcswc', 'lcsw-r', 'lcswr', 'lcswacsw'],
    'Licensed Independent Social Worker': ['lisw'],
    'Master of Social Work': ['msw', 'mssw', 'msa'],
    'Service': ['service', 'svc', 'services'],
    'Law Offices': ['law offices', 'law office'],
}

terms_by_type = {**business_terms, **medical_terms, **lawyer_terms,
                 **real_estate_terms, **insurance_terms, **finance_terms,
                 **other_terms}

terms_by_country = {
    'Albania': ['sh.a.', 'sh.p.k.'],
    'Argentina': [
        's.a.', 's.r.l.', 's.c.p.a', 'scpa', 's.c.e i.', 's.e.', 's.g.r',
        'soc.col.'
    ],
    'Australia': ['nl', 'pty. ltd.', 'pty ltd'],
    'Austria': ['e.u.', 'stg', 'gesbr', 'a.g.', 'ag', 'og', 'kg'],
    'Belarus': ['aat', '3at'],
    'Belgium': [
        'esv', 'vzw', 'vof', 'snc', 'comm.v', 'scs', 'bvba', 'sprl', 'cbva',
        'cvoa', 'sca', 'sep', 'gie'
    ],
    'Bosnia / Herzegovina':
    ['d.d.', 'a.d.', 'd.n.o.', 'd.o.o.', 'k.v.', 's.p.'],
    'Brazil':
    ['ltda', 's.a.', 'pllc', 'ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
    'Bulgaria': ['ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
    'Cambodia': ['gp', 'sm pte ltd.', 'pte ltd.', 'plc ltd.', 'peec', 'sp'],
    'Canada': ['gp', 'lp', 'sp'],
    'Chile': [
        'eirl', 's.a.', 'sgr', 's.g.r.', 'ltda', 's.p.a.', 'sa', 's. en c.',
        'ltda.'
    ],
    'Columbia': ['s.a.', 'e.u.', 's.a.s.', 'suc. de descendants', 'sca'],
    'Croatia': ['d.d.', 'd.d.o.', 'obrt'],
    'Czech Republic': [
        'a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'v.o.s.',
        u've\xc5\x99. obch. spol.', 'a spol.', 'k.s.', 'kom. spol.',
        'kom. spol.'
    ],
    'Denmark': [
        'i/s', 'a/s', 'k/s', 'p/s', 'amba', 'a.m.b.a.', 'fmba', 'f.m.b.a.',
        'smba', 's.m.b.a.', 'g/s'
    ],
    'Dominican Republic':
    ['c. por a.', 'cxa', 's.a.', 's.a.s.', 'srl.', 'eirl.', 'sa', 'sas'],
    'Ecuador': ['s.a.', 'c.a.', 'sa', 'ep'],
    'Egypt': ['sae'],
    'Estonia': ['fie'],
    'Finland': [
        't:mi', 'tmi', 'as oy', 'as.oy', 'ay', 'ky', 'oy', 'oyj', 'ok'
    ],
    'France': [
        'sicav', 'sarl', 'sogepa', 'ei', 'eurl', 'sasu', 'fcp', 'gie', 'sep',
        'snc', 'scs', 'sca', 'scop', 'sem', 'sas'
    ],
    'Germany': [
        'gmbh & co. kg', 'gmbh & co. kg', 'e.g.', 'e.v.', 'gbr', 'ohg',
        'partg', 'kgaa', 'gmbh', 'g.m.b.h.', 'ag'
    ],
    'Greece': [
        'a.e.', 'ae', 'e.e.', 'ee', 'epe', 'e.p.e.', 'mepe', 'm.e.p.e.',
        'o.e.', 'oe', 'ovee', 'o.v.e.e.'
    ],
    'Guatemala': ['s.a.', 'sa'],
    'Haiti': ['sa'],
    'Hong Kong': ['ltd', 'unltd', 'ultd', 'limited'],
    'Hungary': [
        'e.v.', 'e.c.', 'bt.', 'kft.', 'kht.', 'kkt.', 'k.v.', 'zrt.', 'nyrt',
        'ev', 'ec', 'rt.'
    ],
    'Iceland': ['ehf.', 'hf.', 'ohf.', 's.f.', 'ses.'],
    'India': ['pvt. ltd.', 'ltd.', 'psu', 'pse'],
    'Indonesia': ['ud', 'fa', 'pt'],
    'Ireland': ['cpt', 'teo'],
    'Israel': ['b.m.', 'bm', 'ltd', 'limited'],
    'Italy': [
        's.n.c.', 's.a.s.', 's.p.a.', 's.a.p.a.', 's.r.l.', 's.c.r.l.', 's.s.'
    ],
    'Latvia': ['as', 'sia', 'ik', 'ps', 'ks'],
    'Lebanon': ['sal'],
    'Lithuania': ['uab', 'ab', 'ij', 'mb'],
    'Luxemborg': ['s.a.', 's.a.r.l.', 'secs'],
    'Macedonia': ['d.o.o.', 'd.o.o.e.l', 'k.d.a.', 'j.t.d.', 'a.d.', 'k.d.'],
    'Malaysia': ['bhd.', 'sdn. bhd.'],
    'Mexico': ['s.a.', 's. de. r.l.', 's. en c.', 's.a.b.', 's.a.p.i.'],
    'Mongolia': ['xk', 'xxk'],
    'Netherlands': ['v.o.f.', 'c.v.', 'b.v.', 'n.v.'],
    'New Zealand': ['tapui', 'ltd', 'limited'],
    'Nigeria': ['gte.', 'plc', 'ltd.', 'ultd.'],
    'Norway': [
        'asa', 'as', 'ans', 'ba', 'bl', 'da', 'etat', 'fkf', 'hf', 'iks', 'kf',
        'ks', 'nuf', 'rhf', 'sf'
    ],
    'Oman': ['saog', 'saoc'],
    'Pakistan': ['ltd.', 'pvt. ltd.', 'ltd', 'limited'],
    'Peru': ['sa', 's.a.', 's.a.a.'],
    'Philippines':
    ['coop.', 'corp.', 'corp', 'ent.', 'inc.', 'inc', 'llc', 'l.l.c.', 'ltd.'],
    'Poland': [
        'p.p.', 's.k.a.', 'sp.j.', 'sp.k.', 'sp.p.', 'sp. z.o.o.', 's.c.',
        's.a.'
    ],
    'Portugal': ['lda.', 'crl', 's.a.', 's.f.', 'sgps'],
    'Romania': ['s.c.a.', 's.c.s.', 's.n.c.', 's.r.l.', 'o.n.g.', 's.a.'],
    'Russia': ['ooo', 'oao', 'zao', '3ao'],
    'Serbia': ['d.o.o.', 'a.d.', 'k.d.', 'o.d.'],
    'Singapore': ['bhd', 'pte ltd', 'sdn bhd', 'llp', 'l.l.p.', 'ltd.', 'pte'],
    'Slovenia': ['d.d.', 'd.o.o.', 'd.n.o.', 'k.d.', 's.p.'],
    'Slovakia': [
        'a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'k.s.', 'kom. spol.',
        'v.o.s.', 'a spol.'
    ],
    'Spain': [
        's.a.', 's.a.d.', 's.l.', 's.l.l.', 's.l.n.e.', 's.c.', 's.cra',
        's.coop', 'sal', 'sccl'
    ],
    'Sweden': ['ab', 'hb', 'kb'],
    'Switzerland': ['ab', 'sa', 'gmbh', 'g.m.b.h.', 'sarl', 'sagl'],
    'Turkey': ['koop.'],
    'Ukraine': [
        'dat', 'fop', 'kt', 'pt', 'tdv', 'tov', 'pp', 'vat', 'zat', 'at'
    ],
    'United Kingdom': [
        'plc.', 'plc', 'cic', 'cio', 'l.l.p.', 'llp', 'l.p.', 'lp', 'ltd.',
        'ltd', 'limited'
    ],
    'United States of America': [
        'llc', 'inc.', 'corporation', 'incorporated', 'company', 'limited',
        'corp.', 'inc.', 'inc', 'llp', 'l.l.p.', 'pllc', 'and company',
        '& company', 'inc', 'inc.', 'corp.', 'corp', 'ltd.', 'ltd', '& co.',
        '& co', 'co.', 'co', 'lp'
    ],
    'Uzbekistan': [
        'mchj', 'qmj', 'aj', 'oaj', 'yoaj', 'xk', 'xt', 'ok', 'uk', 'qk'
    ]
}
